[package]
name = "smalltask"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
multitask = "0.2"
num_cpus = "1"
parking = "1"
pollster = "0.2"
futures-util = "0.3.5"
